--@noindex
--NoIndex: true

WIDGETS_LIVE_UPDATE_SPEED = 10 -- FRAMES

-- EDGE GRAG SCROLLING
EDGE_SCROLLING_ZONE = 80
EDGE_SCROLLING_SPEED = 5

-- ENABLE GRID
GRID = true
GRID_SIZE = 32 -- grid cell size in canvas units (drives grid drawing AND node snapping)

-- BACKGROUND COLOR TOGGLE
-- false = current gray bg, true = attached (sampled) bg
BG_ATTACHED = false
BG_COLOR_CURRENT  = 0x333333ff -- current gray bg
BG_COLOR_ATTACHED = 0x181818ff -- attached bg (rgb 40,40,40)

-- THRESHOLD FOR NEW PROJECT SAVE PROMPT
NEW_PROJECT_NODE_CONDITION = 1

-- FONT SIZE FOR ZOOMING (UPDATES ON ZOOM - EVERYTHING IN NODE)
FONT_SIZE = 16
ORG_FONT_SIZE = FONT_SIZE

-- STATIC FONT SIZE (WONT UPDATE ON ZOOM - TOOLTIPS)
FONT_SIZE_STATIC = 15

TOOLTIP = true
DEBUG = false
PROFILE_DEBUG = false

PROJECT_NAME = 'Untitled Spaghetti'
